# Generated by Django 2.2.6 on 2019-11-04 16:29

import address.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0002_auto_20160213_1726'),
        ('user', '0003_auto_20191031_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown Act', max_length=120)),
                ('type', models.CharField(default='Unknown Type', max_length=50)),
                ('length', models.PositiveSmallIntegerField(default=0)),
                ('picture', models.ImageField(upload_to='')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='John Doe', max_length=120)),
                ('year', models.PositiveSmallIntegerField(default=0)),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='John Doe', max_length=120)),
                ('year', models.PositiveSmallIntegerField(default=0)),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='act_of_event', to='cinema.Act')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown Genre', max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats_count', models.PositiveSmallIntegerField(default=0)),
                ('address', address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveSmallIntegerField(default=0)),
                ('seat_No', models.PositiveSmallIntegerField(default=0)),
                ('is_available', models.BooleanField(default=False)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corresponding_hall', to='cinema.Hall')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_event', to='cinema.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_maker', to='user.NotRegistered')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_hall', to='cinema.Hall'),
        ),
        migrations.AddField(
            model_name='act',
            name='cast',
            field=models.ManyToManyField(to='cinema.Actor'),
        ),
        migrations.AddField(
            model_name='act',
            name='director',
            field=models.ManyToManyField(to='cinema.Director'),
        ),
        migrations.AddField(
            model_name='act',
            name='genre',
            field=models.ManyToManyField(to='cinema.Genre'),
        ),
    ]
