# Generated by Django 2.2.6 on 2019-10-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='length',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='hall',
            name='seats_count',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='seat',
            name='row',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_No',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
