# Generated by Django 2.2.6 on 2019-11-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='address',
        ),
        migrations.AddField(
            model_name='hall',
            name='name',
            field=models.CharField(default='Unknown Hall', max_length=120),
        ),
    ]
