# Generated by Django 2.2.6 on 2019-11-09 19:01

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street1', models.CharField(blank=True, max_length=300)),
                ('street2', models.CharField(default='Unknown street', max_length=300)),
                ('houseNumber', models.CharField(default='Unknown number', max_length=300)),
                ('city', models.CharField(default='Unknown city', max_length=300)),
                ('psc', models.CharField(default='Unknown ZIP code', max_length=30)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'unique_together': {('street1', 'street2', 'houseNumber', 'city', 'psc', 'country')},
            },
        ),
    ]
