# Generated by Django 2.2.6 on 2019-10-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notregistered',
            name='email',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='notregistered',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='notregistered',
            name='surname',
            field=models.TextField(max_length=120),
        ),
    ]
