# Generated by Django 2.2.6 on 2019-11-01 13:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191031_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('registered_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.Registered')),
            ],
            bases=('user.registered',),
        ),
        migrations.CreateModel(
            name='Redactor',
            fields=[
                ('registered_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.Registered')),
            ],
            bases=('user.registered',),
        ),
        migrations.RemoveField(
            model_name='registered',
            name='address',
        ),
        migrations.AddField(
            model_name='registered',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2019, 11, 1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notregistered',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
